"""empty message

Revision ID: 4124da07b326
Revises:
Create Date: 2022-05-02 10:16:31.495728

"""


# revision identifiers, used by Alembic.
revision = "4124da07b326"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
